name: auth0_lib
description: "Flutter toolkit for Auth0 API and web pkce flow authentication. Forked: https://github.com/devdennysegura/flutter-auth0"
author: BitsCR <dev@bits.cr>
homepage: https://github.com/bits-cr/flutter-auth0-lib
version: 0.5.1

environment:
  sdk: ">=2.1.0 <3.0.0"
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  meta: ^1.1.6
  http: ^0.12.0+2
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.6.5

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.flutterauth0
        pluginClass: FlutterAuth0Plugin